////
*******************************************************************
* Copyright (c) 2019 Eclipse Foundation
*
* This specification document is made available under the terms
* of the Eclipse Foundation Specification License v1.0, which is
* available at https://www.eclipse.org/legal/efsl.php.
*******************************************************************
////

[[relationship_to_other_specifications]]
=== Relationship to Other Specifications

The Jakarta EE Platform specification requires
support for interceptors. The use of interceptors defined by means of
the _Interceptors_ annotation is required to be supported for EJB and
Managed Bean components, including in the absence of CDI. When CDI is
enabled, the use of interceptors defined both by means of interceptor
binding annotations and by means of the _Interceptors_ annotation is
required to be supported for component classes that support injection,
as described in the section “Annotations and Injection” of the Jakarta EE
Platform specification link:intercept.html#a546[See Jakarta EE Platform 9.
https://jakarta.ee/specifications/platform/9/.].

Both the EJB and the CDI specifications
provide extensions to this specification. Other specifications may
choose to do so in the future. Such specifications are referred to in
this document as extension specifications. This document outlines
permissible extensions to this specification and defines requirements
for extension specifications.
