////
*******************************************************************
* Copyright (c) 2019 Eclipse Foundation
*
* This specification document is made available under the terms
* of the Eclipse Foundation Specification License v1.0, which is
* available at https://www.eclipse.org/legal/efsl.php.
*******************************************************************
////

[[revision_history]]
=== Revision History

This document is an update to the
Interceptors specification 1.2. Version 1.1 was based on the
Interceptors chapter of the Enterprise JavaBeansTM 3.0 (EJB)
specification link:intercept.html#a541[See Enterprise
JavaBeansTM, version 3.0. http://jcp.org/en/jsr/detail?id=220.]. Version
1.2 included interceptor binding definitions that were originally
defined in the Contexts and Dependency Injection for the Java EE
Platform (CDI) specification link:intercept.html#a543[See
Contexts and Dependency Injection for the Java EE Platform 1.1 (CDI
specification) http://jcp.org/en/jsr/detail?id=346.].

The change log for the current version is found in <<change_log>>.
