////
*******************************************************************
* Copyright (c) 2019 Eclipse Foundation
*
* This specification document is made available under the terms
* of the Eclipse Foundation Specification License v1.0, which is
* available at https://www.eclipse.org/legal/efsl.php.
*******************************************************************
////

[[enabling_interceptors]]
=== Enabling Interceptors

Only interceptors that are enabled are
eligible to be invoked.

Interceptors declared using interceptor
bindings are enabled using the Priority annotation (see Section
<<use_of_the_priority_annotation_in_ordering_interceptors>>).
The _Priority_ annotation also controls
interceptor ordering (see Section <<interceptor_ordering_rules>>).

Interceptors declared using the
_Interceptors_ annotation are enabled by that annotation. Using the
_Interceptors_ annotation to associate interceptor classes with a target
class or a method or constructor of a target class enables them for that
target class, method, or constructor. The order in which the interceptor
classes are specified in the _Interceptors_ annotation controls
interceptor ordering (see Section <<interceptor_ordering_rules>>).
Interceptor methods declared in the target
class or in a superclass of the target class are enabled unless
overridden.

An extension specification may define
alternative mechanisms (e.g., a deployment descriptor such as the CDI
beans.xml <<bib3>> or the EJB _ejb-jar.xml_
deployment descriptor <<bib2>>) to
enable and order interceptors, to override the order specified by means
of annotations, or to disable interceptors.

Note: The _InvocationContext_ object allows
interceptor methods to control the behavior of the invocation chain,
including whether the next method in the chain is invoked and the values
of its parameters and result. See Section
<<invocation_context>>.
