////
*******************************************************************
* Copyright (c) 2019 Eclipse Foundation
*
* This specification document is made available under the terms
* of the Eclipse Foundation Specification License v1.0, which is
* available at https://www.eclipse.org/legal/efsl.php.
*******************************************************************
////

[[excluding_interceptors]]
== Excluding Interceptors

Interceptors may be excluded from execution
by means of the _ExcludeClassInterceptors_ annotation and the
_ExcludeDefaultInterceptors_ annotation.

The _ExcludeClassInterceptors_ annotation can
be used to exclude the invocation of the class-level interceptors
defined by means of the _Interceptors_ annotation.

The _ExcludeDefaultInterceptors_ annotation
can be used to exclude the invocation of default interceptors for a
target class or—when applied to a target class constructor or method—to
exclude the invocation of default interceptors for a particular
constructor or method.

An extension specification may define other
means for excluding interceptors from execution, such as by means of a
deployment descriptor.



In the following example interceptors will be
invoked in the following order when _someMethod_ is called:
SomeInterceptor, AnotherInterceptor, MyInterceptor.

@Stateless

@Interceptors(\{org.acme.SomeInterceptor.class,

 org.acme.AnotherInterceptor.class})

public class MyBean \{

 ...

 @Interceptors(org.acme.MyInterceptor.class)

 public void someMethod() \{

 ...

 }

}

In the following example only the interceptor
_MyInterceptor_ will be invoked when _someMethod_ is called. The
_ExcludeClassInterceptors_ annotation is used to exclude the invocation
of the class-level interceptors.

@Stateless

@Interceptors(org.acme.AnotherInterceptor.class)

public class MyBean \{

 ...

 @Interceptors(org.acme.MyInterceptor.class)

 @ExcludeClassInterceptors

 public void someMethod() \{

 ...

 }

}

In the next example, only the interceptor
_MyInterceptor_ will be invoked when _someMethod_ is called. The
_ExcludeDefaultInterceptors_ annotation is used to exclude the
invocation of the default interceptors (if any).

@Stateless

public class MyBean \{

 ...

 @ExcludeDefaultInterceptors

 @Interceptors(org.acme.MyInterceptor.class)

 public void someMethod() \{

 ...

 }

}
