////
*******************************************************************
* Copyright (c) 2019 Eclipse Foundation
*
* This specification document is made available under the terms
* of the Eclipse Foundation Specification License v1.0, which is
* available at https://www.eclipse.org/legal/efsl.php.
*******************************************************************
////

[[interceptor_resolution]]
== Interceptor Resolution

The process of matching interceptors to a
given business method, timeout method, or lifecycle event of a component
is called _interceptor resolution_ .

For a lifecycle event other than instance
construction, the interceptor bindings include the interceptor bindings
declared or inherited by the component at the class level, including,
recursively, interceptor bindings declared as meta-annotations of other
interceptor bindings.

For a business method, timeout method, or
constructor, the interceptor bindings include the interceptor bindings
declared or inherited by the component at the class level, including,
recursively, interceptor bindings declared as meta-annotations of other
interceptor bindings, together with all interceptor bindings declared on
the constructor or method, including, recursively, interceptor bindings
declared as meta-annotations of other interceptor bindings.

An interceptor is bound to a method or
constructor if:

The method or constructor has all the
interceptor bindings of the interceptor. A method or constructor has an
interceptor binding of an interceptor if it has an interceptor binding
with (a) the same type and (b) the same annotation member value for each
member. An extension specification may further refine this rule. For
example, the CDI specification link:intercept.html#a543[See
Jakarta Contexts and Dependency Injection (CDI specification), version 3.0.
https://jakarta.ee/specifications/cdi/3.0/.] adds the
jakarta.enterprise.util.Nonbinding annotation, causing member values to be
ignored by the resolution process.

The interceptor intercepts the given kind of
lifecycle event or method.

The interceptor is enabled. An interceptor is
enabled if the _Priority_ annotation is applied to the interceptor
classlink:#a574[8]. An extension specification may define other
means of enabling interceptors. For example, the CDI specification
enables an interceptor if the interceptor class is listed under the
_<interceptors>_ element of the _beans.xml_ file for the bean archive.

