////
*******************************************************************
* Copyright (c) 2019 Eclipse Foundation
*
* This specification document is made available under the terms
* of the Eclipse Foundation Specification License v1.0, which is
* available at https://www.eclipse.org/legal/efsl.php.
*******************************************************************
////

[[interceptor_binding_types_with_additional_interceptor_bindings]]
=== Interceptor binding types with additional interceptor bindings

An interceptor binding type may declare other
interceptor bindings.

@Inherited

@InterceptorBinding

@Target(\{TYPE, METHOD})

@Retention(RUNTIME)

@Monitored

public @interface DataAccess \{}

Interceptor bindings are transitive—an
interceptor binding declared by an interceptor binding type is inherited
by all components and other interceptor binding types that declare that
interceptor binding type.

An interceptor binding type can only be
applied to an interceptor binding type defining a subset of its target
types. For example, interceptor binding types declared Target(TYPE) may
not be applied to interceptor binding types declared Target(\{TYPE,
METHOD}).
