////
*******************************************************************
* Copyright (c) 2019 Eclipse Foundation
*
* This specification document is made available under the terms
* of the Eclipse Foundation Specification License v1.0, which is
* available at https://www.eclipse.org/legal/efsl.php.
*******************************************************************
////

[[interceptor_life_cycle]]
=== Interceptor Life Cycle

The lifecycle of an interceptor instance is
the same as that of the target instance with which it is associated.

Except as noted below, when the target
instance is created, a corresponding instance is created for each
associated interceptor class. These interceptor instances are destroyed
if the target instance fails to be created or when the target instance
is destroyed by the container.

An interceptor instance may be the target of
dependency injection. Dependency injection is performed when the
interceptor instance is created, using the naming context of the
associated target class.

With the exception of around-construct
lifecycle callback interceptor methods, no interceptor methods are
invoked until after dependency injection has been completed on both the
interceptor instances and the target instancelink:#a567[1].

Post-construct interceptor methods for the
target instance are invoked after dependency injection has been
completed on the target instance.

{empty}Pre-destroy interceptor methods are
invoked before the target instance and all interceptor instances
associated with it are destroyed.link:#a568[2]

The following rules apply specifically to
around-construct lifecycle callback interceptor methods:

Around-construct lifecycle callback
interceptor methods are invoked after dependency injection has been
completed on the instances of all interceptor classes associated with
the target class. Injection of the target component into interceptor
instances that are invoked during the around-construct lifecycle
callback is not supported.

The target instance is created _after_ the
last interceptor method in the around-construct interceptor chain
invokes the InvocationContext.proceed method. If the constructor for the
target instance supports injection, such constructor injection is
performed. If the InvocationContext.proceed method is not invoked by an
interceptor method, the target instance will not be created.

An around-construct interceptor method can
access the constructed instance using the InvocationContext.getTarget
method after the InvocationContext.proceed method completes.

Dependency injection on the target instance
other than constructor injection is not completed until after the
invocations of all interceptor methods in the around-construct
interceptor chain complete successfully. Around-construct lifecycle
callback interceptor methods should therefore exercise caution when
invoking methods of the target instance since dependency injection on
the target instance will not have been completed.

include::interceptor_environment.adoc[]
