////
*******************************************************************
* Copyright (c) 2019 Eclipse Foundation
*
* This specification document is made available under the terms
* of the Eclipse Foundation Specification License v1.0, which is
* available at https://www.eclipse.org/legal/efsl.php.
*******************************************************************
////

[[interceptor_environment]]
==== Interceptor Environment

An interceptor class shares the enterprise
naming context of its associated target class. Annotations and/or XML
deployment descriptor elements for dependency injection or for direct
JNDI lookup refer to this shared naming context.

Around-invoke and around-timeout interceptor
methods run in the same Java thread as the associated target method.
Around-construct interceptor methods run in the same Java thread as the
target constructor.

It is possible to carry state across multiple
interceptor method invocations for a single method invocation or
lifecycle callback event in the context data of the _InvocationContext_
object. The _InvocationContext_ object also provides information that
enables interceptor methods to control the behavior of the interceptor
invocation chain, including whether the next method in the chain is
invoked and the values of its parameters and result.
