////
*******************************************************************
* Copyright (c) 2019 Eclipse Foundation
*
* This specification document is made available under the terms
* of the Eclipse Foundation Specification License v1.0, which is
* available at https://www.eclipse.org/legal/efsl.php.
*******************************************************************
////

[[exceptions]]
== Exceptions

Interceptor methods are allowed to throw
runtime exceptions or any checked exceptions that the associated target
method or constructor allows within its _throws_ clause.

Interceptor methods are allowed to catch and
suppress exceptions and to recover by calling the
_InvocationContext.proceed_ method.

The invocation of the
_InvocationContext.proceed_ method throws the same exception as any
thrown by the associated target method unless an interceptor method
further down the Java call stack has caught it and thrown a different
exception or suppressed the exception. Exceptions and initialization
and/or cleanup operations should typically be handled in _try_ / _catch_
/ _finally_ blocks around the _proceed_ method.
